import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

const prototypeScript = readFileSync(resolve(__dirname, '../../prototype/prototype.js'), 'utf8')
const prototypeStyles = readFileSync(resolve(__dirname, '../../prototype/prototype.css'), 'utf8')
const attributionPath = resolve(__dirname, '../../prototype/assets/ATTRIBUTION.md')

describe('prototype atlas composition', () => {
  it('uses a compact bottom-right guide with curved open-surface arches and no tongue ellipse', () => {
    expect(prototypeScript).not.toContain('mouth-gap')
    expect(prototypeScript).toContain('lower-arch')
    expect(prototypeStyles).toMatch(/\.mouth-guide\s*\{[^}]*position:\s*absolute/)
    expect(prototypeStyles).toMatch(/\.mouth-guide\s*\{[^}]*right:\s*16px/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.front \.teeth-row \.tooth:nth-child\(1\)[^}]*--drop:\s*4px[^}]*--tilt:\s*-8deg/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.front\s*\{[^}]*gap:\s*0/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.front \.teeth-row\s*\{[^}]*height:\s*30px/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.front \.teeth-row\.upper-arch\s*\{[^}]*transform:\s*none/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.front \.teeth-row\.lower-arch\s*\{[^}]*transform:\s*rotate\(180deg\)/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.front \.tooth\s*\{[^}]*transform:\s*translateY\(var\(--drop\)\) rotate\(var\(--tilt\)\) rotate\(180deg\)/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.chewing, \.mouth-map\.inside\s*\{[^}]*gap:\s*0/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.chewing \.teeth-row, \.mouth-map\.inside \.teeth-row\s*\{[^}]*height:\s*56px/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.chewing \.teeth-row[^}]*--open-drop/)
    expect(prototypeStyles).toMatch(/\.mouth-map\.inside \.teeth-row[^}]*--open-drop/)
  })

  it('scopes one pastel palette to brushing-session screens', () => {
    expect(prototypeScript).toContain('sessionTones')
    expect(prototypeScript).toContain('tone=')
    expect(prototypeScript).toMatch(/sessionStates\.includes\(state\)/)
    expect(prototypeStyles).toMatch(/\.session-app\s*\{[^}]*--paper:\s*var\(--session-paper\)/)
    expect(prototypeStyles).toMatch(/\.session-app\s*\{[^}]*--butter:\s*var\(--session-light\)/)
    expect(prototypeStyles).toMatch(/\.session-app::before\s*\{[^}]*display:\s*none/)
  })

  it('uses top-surface geometry for inside surfaces and brushes the active row', () => {
    expect(prototypeScript).toContain('toothbrush')
    expect(prototypeScript).toContain('openmoji-toothbrush.svg')
    expect(prototypeScript).toMatch(/const brushPositionIndex = arch === 'lower' \? 2 - activeZone\.positionIndex : activeZone\.positionIndex/)
    expect(prototypeScript).toContain('const brushX = [16.7, 50, 83.3][brushPositionIndex]')
    expect(prototypeScript).toContain('data-arch="${arch}"')
    expect(prototypeScript).not.toContain('class="toothbrush ${activeZone.arch}"')
    expect(prototypeScript).toMatch(/activeZone\.arch === arch/)
    expect(prototypeScript).toContain('aria-hidden="true"')
    expect(prototypeStyles).toMatch(/\.teeth-row\.chewing \.tooth, \.teeth-row\.inside \.tooth\s*\{[^}]*height:\s*25px/)
    expect(prototypeStyles).toContain('@keyframes toothbrush-sweep')
    expect(prototypeStyles).toMatch(/\.toothbrush\s*\{[^}]*animation:\s*toothbrush-sweep/)
    expect(prototypeStyles).toMatch(/@keyframes toothbrush-sweep[\s\S]*translateX\(-8px\)[\s\S]*translateX\(8px\)/)
  })

  it('references a locally licensed toothbrush asset', () => {
    expect(prototypeScript).toContain('./assets/openmoji-toothbrush.svg')
    const attribution = readFileSync(attributionPath, 'utf8')
    expect(attribution).toContain('OpenMoji')
    expect(attribution).toContain('https://raw.githubusercontent.com/hfg-gmuend/openmoji/master/color/svg/1FAA5.svg')
    expect(attribution).toContain('CC BY-SA 4.0')
  })

  it('models the opening, brushing, and closing audiobook acts', () => {
    expect(prototypeScript).toContain("opening: 'Opening audiobook'")
    expect(prototypeScript).toContain("closing: 'Closing audiobook'")
    expect(prototypeScript).toContain("button('Start an adventure', 'opening'")
    expect(prototypeScript).toContain("button('Begin story', 'running'")
    expect(prototypeScript).not.toContain("button('Continue with audio only', 'audioOnly'")
    expect(prototypeScript).toContain("button('Continue to story choice', 'choice'")
    expect(prototypeScript).toContain('preflight: openingScreen')
    expect(prototypeScript).toContain("const sessionStates = ['preflight', 'opening'")
    expect(prototypeScript).toContain("const pageHeading = ['welcome', 'complete'].includes(state)")
  })

  it('keeps the atlas balanced with three, four, and three tooth groups', () => {
    expect(prototypeScript).toContain('Array.from({ length: 10')
    expect(prototypeScript).toContain('positionIndex >= 3 && positionIndex < 7')
    expect(prototypeScript).toContain('positionIndex >= 7 ? 2 : positionIndex >= 3 && positionIndex < 7 ? 1 : 0')
    expect(prototypeStyles).toMatch(/\.teeth-row \.tooth:nth-child\(10\)/)
  })

  it('separates the floating countdown from compact bottom-left playback', () => {
    expect(prototypeScript).toContain('function countdown(')
    expect(prototypeScript).toContain('function countdown(remainingSeconds = 120)')
    expect(prototypeScript).toContain('<span aria-hidden="true">${remainingSeconds}</span>')
    expect(prototypeScript).toContain('aria-label="${remainingSeconds} seconds remaining"')
    expect(prototypeScript).toContain('audio-visualizer')
    expect(prototypeScript).not.toContain('data-seconds=')
    expect(prototypeScript).toContain('class="countdown"')
    expect(prototypeScript).toContain('${cameraPreview()}${countdown()}')
    expect(prototypeStyles).toMatch(/\.playback-wrap\s*\{[^}]*display:\s*flex[^}]*align-items:\s*center[^}]*justify-content:\s*center/)
    expect(prototypeStyles).toMatch(/\.playback-wrap\s*\{[^}]*position:\s*relative/)
    expect(prototypeStyles).toMatch(/\.playback-wrap\s*\{[^}]*width:\s*100px[^}]*max-width:\s*100px/)
    expect(prototypeStyles).toMatch(/\.session-visual\s*\{[^}]*grid-template-columns:\s*minmax\(100px,\s*100px\)\s+minmax\(0,\s*1fr\)/)
    expect(prototypeStyles).toMatch(/\.audio-visualizer\s*\{[^}]*position:\s*absolute[^}]*z-index:\s*0/)
    expect(prototypeStyles).toMatch(/\.playback\s*\{[^}]*z-index:\s*1/)
    expect(prototypeStyles).toMatch(/\.countdown\s*\{[^}]*background:\s*var\(--session-deep\)[^}]*color:\s*var\(--session-paper\)/)
    expect(prototypeStyles).toMatch(/\.countdown\s*\{[^}]*position:\s*relative[^}]*margin:/)
    expect(prototypeStyles).toMatch(/\.audio-visualizer\s*\{[^}]*animation:/)
    expect(prototypeStyles).toMatch(/\.toothbrush img\s*\{[^}]*transform:\s*rotate\(/)
    expect(prototypeStyles).toMatch(/\.toothbrush\s*\{[^}]*width:\s*150px[^}]*height:\s*56px/)
    expect(prototypeStyles).toMatch(/\.toothbrush\s*\{[^}]*left:\s*clamp\(/)
    expect(prototypeStyles).toMatch(/\.mouth-guide\s*\{[^}]*right:\s*16px[^}]*width:\s*min\(calc\(100% - 16px\),\s*210px\)/)
    expect(prototypeStyles).toMatch(/\.tooth\s*\{[^}]*flex:\s*0 0 clamp\(13px,\s*4\.5vw,\s*19px\)/)
    expect(prototypeStyles).toMatch(/\.lower-arch \.toothbrush\s*\{[^}]*left:\s*clamp\(0px,\s*calc\(var\(--brush-x\) - 75px\),\s*calc\(100% - 150px\)\)/)
    expect(prototypeStyles).toMatch(/\.toothbrush img\s*\{[^}]*width:\s*112px[^}]*height:\s*112px/)
  })
})
